Search system
mburko/SecretShop_BE pull request #16
Opened 2022-04-26 07:08 UTC by Magister25

2022-04-26 20:59 UTC, OleksiiDatsiuk requested changes

2022-04-26 20:59 UTC, OleksiiDatsiuk commented on questions/views.py
> +    #При розростанні словника(10+ елементів) створити json файл !
Code comments must be in English

2022-04-28 22:39 UTC, OleksiiDatsiuk approved these changes

2022-04-29 06:54 UTC, NastiaChaikovska approved these changes

2022-04-29 06:55 UTC, merged