9 create answer endpoint
mburko/SecretShop_BE pull request #9
Opened 2022-04-15 22:35 UTC by OleksiiDatsiuk

Few major fixed in all endpoints, also refactored some code

2022-04-15 22:41 UTC, shevchenkoira requested changes
the admin should not be able to change the author for the question/answer

2022-04-15 22:46 UTC, OleksiiDatsiuk commented
Admin role isnt implemented yet, so no one can change authority

2022-04-15 22:49 UTC, shevchenkoira approved these changes

2022-04-16 09:22 UTC, txmxrxrxnxi approved these changes

2022-04-16 09:26 UTC, merged